FROM node:lts

WORKDIR /app

# Copie les fichiers de dépendances
COPY package*.json ./
RUN npm install && npm install @tailwindcss/postcss

# Copie le code source du frontend
COPY . .
EXPOSE 3000

# Commande de démarrage du serveur Vue
CMD [ "npm", "run", "dev", "--", "--host" ]
