services:

  backend:
    build:
      context: . # Construit l'image à partir de la racine du projet
      dockerfile: Dockerfile.backend # Utilise le Dockerfile dédié au backend
    container_name: symfony_api # Nom du conteneur
    ports:
      - "8000:8000" # Expose le port 8000 pour accéder à l'API
    volumes:
      - /app/vendor

    depends_on:
      - database

    environment:
      DATABASE_URL: mysql://user:password@database:3306/dbname


  frontend:
    build:
      context: ./frontend # Construit l'image à partir du dossier frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend_vue
    restart: unless-stopped
    ports:
        - "3000:3000"
    entrypoint: ["npm", "run", "dev"]



  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  default:
    driver: bridge
